---
- name: Update macOS software and Homebrew
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Check for available macOS software updates
      shell: softwareupdate -l
      register: mac_updates
      ignore_errors: yes

    - name: Install all available macOS software updates
      shell: softwareupdate -i -a >> >> /Users/bermekbukair/update_log.txt
      when: mac_updates.rc == 0

    - name: Update Homebrew
      shell: brew update >> >> /Users/bermekbukair/update_log.txt 2>&1

    - name: Upgrade Homebrew packages
      shell: brew upgrade >> >> /Users/bermekbukair/update_log.txt 2>&1

    - name: Clean up Homebrew cache
      shell: brew cleanup >> >> /Users/bermekbukair/update_log.txt 2>&1
